[tool.poetry]
name = "baskteball-statistics-telegram-bot"
version = "0.1.0"
description = "Telegram bot for parsing amateuer basketball leags (MLBL, ABL, BCL) and use it for analyzies"
authors = ["Nikita Veselenko <nikvesel@mail.ru>"]
readme = "README.md"
packages = []

[tool.black]
line-length = 100

[tool.isort]
multi_line_output = 3
line_length = 100
include_trailing_comma = true


[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.2"
pydantic = "^2.10.1"
pydantic-settings = "^2.6.1"
matplotlib = "^3.9.2"
numpy = "^2.1.3"
plotly = "^5.24.1"
python-telegram-bot = "^21.7"
sqlalchemy = "^2.0.36"
alembic = "^1.14.0"
aiosqlite = "^0.20.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
