name: Deploy Telegram Bot

on:
  push:
    branches: [master]

# Обязательные разрешения для OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Получение OIDC-токена через встроенный метод
      - name: Get OIDC Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const coredemo = require('@actions/core')
            const id_token = await core.getIDToken()
            coredemo.setOutput('id_token', id_token)

      # Обмен OIDC-токена на IAM-токен Yandex Cloud
      - name: Get IAM Token
        id: iam-token
        run: |
          SA_ID="aje1d68b9edtrrd8rnjo"  # ID сервисного аккаунта
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
            -d "requested_token_type=urn:ietf:params:oauth:token-type:access_token" \
            -d "audience=$SA_ID" \
            -d "subject_token=${{ steps.oidc.outputs.id_token }}" \
            -d "subject_token_type=urn:ietf:params:oauth:token-type:id_token" \
            "https://auth.yandex.cloud/oauth/token")

          IAM_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "IAM_TOKEN=$IAM_TOKEN" >> $GITHUB_ENV

      # Получение секрета из Lockbox
      - name: Get Lockbox Secret
        run: |
          SECRET_ID="e6qmama9h88knjvgsmcc"  # ID секрета
          PAYLOAD=$(curl -s -H "Authorization: Bearer ${{ env.IAM_TOKEN }}" \
            "https://payload.lockbox.api.cloud.yandex.net/lockbox/v1/secrets/$SECRET_ID/payload")
          
          # Пример извлечения значения секрета
          SECRET_VALUE=$(echo "$PAYLOAD" | jq -r '.entries[] | select(.key == "my-key") | .textValue')
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV